#pragma once

#    undef RGBLIGHT_LIMIT_VAL
#    define RGBLIGHT_LIMIT_VAL 120
#    define RGBLIGHT_DEFAULT_HUE 180
#    define RGBLIGHT_DEFAULT_SAT UINT8_MAX
#    define RGBLIGHT_DEFAULT_VAL RGBLIGHT_LIMIT_VAL
#    define RGBLIGHT_SLEEP